version: '3'
services:
  mssql:
    image: microsoft/mssql-server-linux:latest
    container_name: mssql
    hostname: mssql.local
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: MyStr0ngPassw0rd!
    ports:
      - '1433:1433'

  interlok:
    image: adaptris-labs/interlok-mssql:latest
    container_name: interlok
    hostname: interlok.local
    environment:
      JVM_ARGS: -Xmx1G
      JAVA_OPTS: -Dinterlok.db.url=jdbc:sqlserver://mssql:1433 -Dinterlok.db.user=sa -Dinterlok.db.password=MyStr0ngPassw0rd!
    ports:
      - '8080:8080'
    depends_on:
      - mssql
    links:
      - mssql:mssql


